base_url = "https://lucasizena.github.io"

title = "lucasizena.github.io"
description = "A blog by Lucas Izena"
author = "Lucas Izena"
default_language = "en"

compile_sass = false
minify_html = true
generate_feeds = true
feed_filenames = ["atom.xml"]
taxonomies = [
  { name = "tags", feed = true },
]

[markdown]
bottom_footnotes = true

[extra]
tagline = "A blog by Lucas Izena"

pinned_posts = [
    "first-post.md",
    "IMO-2009-2.md",
]

math_particles_enabled = false
